services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    
    Harryn\Jacobn\SupportCenterBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Package,Templates,Migrations,Tests}'
    
    Harryn\Jacobn\SupportCenterBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
    
    Harryn\Jacobn\SupportCenterBundle\Fixtures\:    
        resource: '../../Fixtures/*'
        tags: ['doctrine.fixture.orm']
